### ISSUE TITLE
feat: wip更新

### ISSUE THREAD

**Issue by hunjixin** [GitDataAI/jiaozifs-ui#124]
如果wip关联的branch已经更新了

需要进行检查，如果更新 显示一个更新按钮

点击更新按钮，发送一个updatewip的请求，把basecommit更新到最新的branch提交上

**Comment by TsumikiQAQ** [comment]
![image](https://github.com/GitDataAI/jiaozifs-ui/assets/116857998/97cfa7c4-0566-4177-b48d-01caf45be89a)
![image](https://github.com/GitDataAI/jiaozifs-ui/assets/116857998/ac42daf5-7b85-4ae0-83c7-460e03521c57)
